NIFTY50_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS", "NESTLEIND.NS",
    "HCLTECH.NS", "POWERGRID.NS", "JSWSTEEL.NS", "ONGC.NS",
    "NTPC.NS", "M&M.NS", "TECHM.NS", "BAJAJFINSV.NS", "INDUSINDBK.NS",
    "ADANIENT.NS", "ADANIPORTS.NS", "COALINDIA.NS", "GRASIM.NS", "HDFCLIFE.NS",
    "DIVISLAB.NS", "EICHERMOT.NS", "TATASTEEL.NS", "BRITANNIA.NS", "BPCL.NS",
    "HEROMOTOCO.NS", "APOLLOHOSP.NS", "CIPLA.NS", "DRREDDY.NS", "SBILIFE.NS",
    "UPL.NS", "BAJAJ-AUTO.NS", "LTIM.NS", "SHRIRAMFIN.NS", "TRENT.NS"
]
